# https://alacritty.org/config-alacritty.html

[general]
import = [
    # https://github.com/alacritty/alacritty-theme
    "themes/themes/argonaut.toml"
]
working_directory = "~"

[terminal]
shell = { program = "wsl.exe", args = ["--cd", "~"] }

[font]
size = 12
normal.family = "FiraCode Nerd Font"
normal.style = "Regular"

[window]
decorations = "Full"
dimensions.columns = 160
dimensions.lines = 46
padding.x = 10
padding.y = 10

