#!/usr/bin/env bash

set -e

CONFIG="install.conf.json"
DOTBOT_BIN="dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

python3 -m pip install --upgrade --user dotbot
cd "${BASEDIR}"
"${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
