add_newline = false
prompt_order = [
    "username",
    "hostname",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "package",
    "python",
    "nix_shell",
    "memory_usage",
    "env_var",
    "cmd_duration",
    "line_break",
    "jobs",
    "battery",
    "time",
    "character",
]

[hostname]
ssh_only = false

[username]
show_always = true
