add_newline = false

format = """\
    $username\
    $hostname\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $package\
    $python\
    $nix_shell\
    $memory_usage\
    $cmd_duration\
    $line_break\
    $jobs\
    $battery\
    $time\
    $env_var\
    $character\
    """

[hostname]
ssh_only = false

[username]
show_always = true
format = "[$user]($style) at "

[package]
disabled = true

[python]
disabled = true

[nix_shell]
disabled = true

[git_branch]
format = "on [$branch]($style) "

[env_var]
variable = "PROMPT_EMOJI"
default = "✨✨✨"
format = "[$env_value]($style) "
