export PATH=$HOME/bin:$HOME/.local/bin:$PATH
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

## Pyenv
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - zsh)"
eval "$(pyenv virtualenv-init -)"

## ZSH configs
##
export ZSH="$HOME/.oh-my-zsh"
# move .zcomdump-* files from home dir
export ZSH_COMPDUMP=$ZSH/cache/.zcompdump-$HOST

ZSH_THEME="kennethreitz"
HYPHEN_INSENSITIVE="true"
HIST_STAMPS="dd.mm.yyyy"
ZSH_PYENV_VIRTUALENV=false

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git helm kubectl kubectx nvm pyenv python vscode)

zstyle ':omz:update' mode reminder  # just remind me to update when it's time
zstyle ':omz:plugins:nvm' lazy yes
zstyle ':omz:plugins:nvm' lazy-cmd copilot

source $ZSH/oh-my-zsh.sh


## User configuration

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

## Prompt tweaks
RPS1="$RPS1"'$(kubectx_prompt_info)'
# TODO pyenv_prompt_info

[[ -f "/usr/sbin/wsl2-ssh-agent" ]] && eval "$(/usr/sbin/wsl2-ssh-agent)"

eval "$(uv generate-shell-completion zsh)"
eval "$(uvx --generate-shell-completion zsh)"
eval "$(kubectl completion zsh)"
eval "$(zoxide init zsh)"

alias lg=lazygit
alias ld=lazydocker

if [[ -o interactive ]]; then
    fastfetch
fi

